### ISSUE TITLE
Pls add my contacts 

### ISSUE THREAD

**Issue by fehrhart** [hcnv/hcnv.github.io#9]
Friederike (Freddie) Ehrhart
hCNV community contributor

- assistant professor 
- Department of Bioinformatics, Maastricht University
- ELIXIR-NL
- ELIXIR rare disease community

email friederike.ehrhart@maastrichtuniversity.nl
website https://www.maastrichtuniversity.nl/f-ehrhart

**Comment by mbaudis** [comment]
Thanks - addressed in https://github.com/hcnv/hcnv.github.io/commit/c1507b249e071860205f9d6eff8c5571e4f029e4
